name: BetterHoeHarvester
version: '1.0.0'
main: com.nours.betterhoeharvester.BetterHoeHarvester
api-version: '1.20'
depend:
  - ProtocolLib
  - WorldGuard
commands:
  betterhoe:
    description: See all BetterHoeHarvester commands
    usage: /betterhoe
    permission: betterhoeharvester.command
    aliases: [bh]
